#+TITLE: Org-mode for everything
#+DATE: 2016-08-20

[[http://orgmode.org][Org-mode]] is a useful emacs mode for [[http://pseudofish.com/using-deft-mode-for-notes-in-emacs.html][note taking]]. Recently, I have been
extending my use of it to include blogging and my emacs config.

Blogging with org-mode can be done using the [[https://github.com/getpelican/pelican-plugins/tree/master/org_reader][org_reader]] plugin for [[http://blog.getpelican.com][pelican]].
There are other blog platforms that integrate org-mode, however this is the
one I'm using. This means I can write an org-mode [[https://github.com/gmwils/pseudofish/blob/master/content/musings/org-mode-for-everything.org][file]] that is generated into
the blog.

Using org-mode for emacs config is a good example of [[https://en.wikipedia.org/wiki/Literate_programming][literate programming]]. It
is both easy to modify and self documenting. Github provides support for org
docs, so my emacs config is viewable [[https://github.com/gmwils/dotfiles/blob/master/emacs.d/gmwils.org][here]].

By using org mode for config, it becomes normal to document why you have
particular configuration settings. Given how complex configuring emacs usually
is, this makes it more sane. The other win is that you can group settings by
using org headings.

I use [[https://www.emacswiki.org/emacs/Yasnippet][yasnippet]] to automate creating most documents, such as a [[https://github.com/gmwils/dotfiles/blob/master/emacs.d/snippets/org-mode/blog][blog]] entry.
This helps with not having to remember specific formatting or metadata for
different document types. This is useful for conducting interviews. I have
created org templates for each role with criteria I want to assess and
a range of questions. Then I just create a new doc, add the template, and go.
